/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/components/layout/AdminLayout.vue')['default']
    AppDateTimePicker: typeof import('./src/components/common/AppDateTimePicker.vue')['default']
    AppSelect: typeof import('./src/components/common/AppSelect.vue')['default']
    CategoryIcon: typeof import('./src/components/common/CategoryIcon.vue')['default']
    DefaultLayout: typeof import('./src/components/layout/DefaultLayout.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ItemPrice: typeof import('./src/components/common/ItemPrice.vue')['default']
    LevelBadge: typeof import('./src/components/common/LevelBadge.vue')['default']
    OrderReviewDialog: typeof import('./src/components/trade/OrderReviewDialog.vue')['default']
    PriceTag: typeof import('./src/components/common/PriceTag.vue')['default']
    ReputationRadar: typeof import('./src/components/common/ReputationRadar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SellerDetailDialog: typeof import('./src/components/user/SellerDetailDialog.vue')['default']
    TagInput: typeof import('./src/components/common/TagInput.vue')['default']
    TagList: typeof import('./src/components/common/TagList.vue')['default']
    UserAvatar: typeof import('./src/components/common/UserAvatar.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
